Repository geoadmin/service-icons, pull requests merged in 2021-11, with the labels that each got.

#41 BGDIINF_SB-2027: Added Cache-Control header and updated ALLOWED_DOMAIN default value
  .pylintrc
  README.md
  app/__init__.py
  app/settings.py
  tests/unit_tests/base_test.py
  tests/unit_tests/test_all_icons.py
  tests/unit_tests/test_checker.py
  tests/unit_tests/test_endpoints_compliance.py
  tests/unit_tests/test_icons.py
  wsgi.py
Labels: feature

#43 added GET method to checker endpoint
  app/routes.py
Labels: skip-release-note

#42 BGDIINF_SB-2027: Fixed CORS headers
  app/__init__.py
  app/helpers/url.py
  app/routes.py
  app/settings.py
  tests/unit_tests/base_test.py
  tests/unit_tests/test_all_icons.py
  tests/unit_tests/test_endpoints_compliance.py
  tests/unit_tests/test_icons.py
Labels: bug

#44 Add PR auto Title Workflow and updated PR labeler
  .github/workflows/pr-labeler.yml
  .github/workflows/pr-semver-release-title.yml
Labels: skip-release-note

#45 Consolidate PR workflows
  .github/workflows/pr-auto-semver.yml
  .github/workflows/pr-labeler.yml
  .github/workflows/semver.yml
Labels: skip-release-note

#47 Renamed the workflow templates
  .github/workflows/pr-auto-semver.yml
  .github/workflows/semver.yml
Labels: skip-release-note
